services:
  speech-admin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: speech-admin
    image: speech-admin
    ports:
      - '127.0.0.1:3033:3000'
    env_file:
      - .env.production
    networks:
      - speech-network
    restart: unless-stopped

networks:
  speech-network:
    external: true
